import Head from 'next/head'
import { CardProducts, Navbar } from '../components'

export default function Home({ shorts }) {
  console.log(shorts)

  return (
    <div>
      <Head>
        <title>VOLK&apos;S | SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        {shorts.map((short) => (
          <CardProducts key={short.id} data={short} />
        ))}
      </main>
    </div>
  )
}

// Si utlizamos esta función, estaremos usando SSR
export async function getServerSideProps() {
  const productosRequest = await fetch('http://localhost:3000/api/shorts')

  const shorts = await productosRequest.json()

  return {
    props: {
      shorts
    }
  }
}
