import Head from 'next/head'
import {
  Navbar,
  Banner,
  Footer,
  Benefits,
  NameSection,
  FrequentQuestions
} from '../components'
import dynamic from 'next/dynamic'
import CardCategory from '../components/cardCategory/CardCategory'

const RandomProductsDynamic = dynamic(
  () => import('../components/randomProducts/RandomProducts'),
  {
    ssr: false
  }
)

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>VOLK&apos;S | SHOP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Navbar />
      </header>

      <main>
        <Banner />
      </main>

      <NameSection title={'Our Benefits'} />
      <Benefits />

      <NameSection title={'Categorys'} />
      <CardCategory />

      <NameSection title={'Random Products'} />
      <RandomProductsDynamic products={products} />

      <NameSection title={'Frequent Questions'} />
      <FrequentQuestions />

      <Footer />
    </>
  )
}

export async function getServerSideProps() {
  const allProducts = await fetch('http://localhost:3000/api/allProducts')

  const products = await allProducts.json()

  return {
    props: {
      products
    }
  }
}
